#ifndef H_SYSTEM_CONFIG
#define H_SYSTEM_CONFIG

#define MAX_WORD_LENGTH 128
#define LAUNCHER_PROMPT_LENGTH 128
#define MAX_LAUNCHER_HINTS 10
#define MAX_WORKSPACES 10
#define MAX_INFO_BLOCKS 10
#define MAX_INFO_TEXT_LENGTH 64
#define MAX_LAUNCHER_HINTS 10
#define MAX_VISIBLE_MINIMIZED 10
#define CLOCK_STEPS_PER_SECOND 10

#define HOR_CELLS_PER_MONITOR 2
#define VERT_CELLS_PER_MONITOR 2
#define CELLS_PER_MONITOR 4
#define GRID_AXIS 2

#endif
