#ifndef H_SYSTEM_CONFIG
#define H_SYSTEM_CONFIG

#define MAX_WORD_LENGTH 128
#define LAUNCHER_PROMPT_LENGTH 128
#define MAX_LAUNCHER_HINTS 10
#define MAX_WORKSPACES 10
#define MAX_INFO_BLOCKS 10
#define MAX_INFO_TEXT_LENGTH 64
#define MAX_LAUNCHER_HINTS 10
#define MAX_VISIBLE_MINIMIZED 10
#define CLOCK_STEPS_PER_SECOND 10

#endif
