#!/bin/env dash

if [ -e "/sys/class/power_supply/BAT1/charge_now" ] &&
   [ -e "/sys/class/power_supply/BAT1/charge_full" ]; then
   charge_now="$(cat /sys/class/power_supply/BAT1/charge_now)"
   charge_full="$(cat /sys/class/power_supply/BAT1/charge_full)"
   percent="$(($charge_now*100/$charge_full))"
   ex=0

   if [ -e "/sys/class/power_supply/BAT1/status" ] &&
      [ "$(cat /sys/class/power_supply/BAT1/status)" != "Discharging" ]; then
     status=""
   elif [ $percent -le 8 ]; then
     status=""
     ex=2
   elif [ $percent -le 16 ]; then
     status=""
     ex=2
   elif [ $percent -le 24 ]; then
     status=""
     ex=1
   elif [ $percent -le 32 ]; then
     status=""
     ex=1
   elif [ $percent -le 40 ]; then
     status=""
   elif [ $percent -le 48 ]; then
     status=""
   elif [ $percent -le 56 ]; then
     status=""
   elif [ $percent -le 64 ]; then
     status=""
   elif [ $percent -le 72 ]; then
     status=""
   elif [ $percent -le 80 ]; then
     status=""
   elif [ $percent -le 88 ]; then
     status=""
   else
     status=""
   fi

   echo "$status $percent%"
   exit "$ex"
fi
