#!/bin/env dash

if [ -e "/sys/class/power_supply/BAT1/charge_now" ] &&
   [ -e "/sys/class/power_supply/BAT1/charge_full" ]; then
   charge_now="$(cat /sys/class/power_supply/BAT1/charge_now)"
   charge_full="$(cat /sys/class/power_supply/BAT1/charge_full)"
   percent="$(($charge_now*100/$charge_full))"
   ex=0

   if [ -e "/sys/class/power_supply/BAT1/status" ] &&
      [ "$(cat /sys/class/power_supply/BAT1/status)" != "Discharging" ]; then
     status=""
   elif [ $percent -le 7 ]; then
     status=""
     ex=2
   elif [ $percent -le 14 ]; then
     status=""
     ex=2
   elif [ $percent -le 21 ]; then
     status=""
     ex=1
   elif [ $percent -le 28 ]; then
     status=""
     ex=1
   elif [ $percent -le 35 ]; then
     status=""
     ex=1
   elif [ $percent -le 42 ]; then
     status=""
   elif [ $percent -le 49 ]; then
     status=""
   elif [ $percent -le 56 ]; then
     status=""
   elif [ $percent -le 63 ]; then
     status=""
   elif [ $percent -le 70 ]; then
     status=""
   elif [ $percent -le 77 ]; then
     status=""
   elif [ $percent -le 84 ]; then
     status=""
   elif [ $percent -le 91 ]; then
     status=""
   elif [ $percent -le 98 ]; then
     status=""
   else
     status=""
   fi

   echo "$status $percent%"
   exit "$ex"
fi
