#!/bin/env dash
dir="/sys/class/backlight/$(ls /sys/class/backlight/ -1 | head -n1)"
if [ "$dir" = "/sys/class/backlight/" ]; then
  exit 1;
fi
current="$(cat "$dir/brightness")"
max="$(cat "$dir/max_brightness")"
if [ -n "$1" ]; then
  curr_percent="$(echo "$current*100/$max+$1" | bc)"
  current="$(echo "$curr_percent*$max/100" | bc)"
  sudo dash -c "echo $current > $dir/brightness"
else
  curr_percent="$(echo "$current*100/$max" | bc)"
fi
echo " $curr_percent%"
