#!/bin/env dash

paused="$(dunstctl is-paused)"
ex=0

if [ "$1" = "toggle" ]; then
  if [ "$paused" = "false" ]; then
    dunstctl set-paused true
    mode=""
  else
    dunstctl set-paused false
    mode=""
    ex=1
  fi
else
  if [ "$paused" = "true" ]; then
    mode=""
  else
    mode=""
    ex=1
  fi
fi

echo "$mode"
exit $ex
