#!/bin/env bash

query="$(nvidia-smi --format=csv --query-gpu=utilization.gpu)"
fp=($query)

if [ "$fp" = "Failed" ]; then
  gpu="Reboot"
else
  gpu="$(echo "$query" | sed '1d' | rev | cut -c3- | rev)"
  if [ -n "$gpu" ] && [ "$gpu" -gt 90 ]; then
    echo "GPU $gpu%"
  else
    echo ""
  fi
fi
