#!/bin/env bash
old="${full_text}"
ex=0

if [ -d /sys/class/net/eth0 ]; then
  if [ "$(cat /sys/class/net/eth0/operstate)" = "up" ]; then
    if [ "$(cat /sys/class/net/eth0/carrier)" = "1" ]; then
      status="󰌘"
    else
      status="󱘖"
      ex=1
    fi
  else
    status="󰌙"
    ex=2
  fi
fi

if [ -d /sys/class/net/wlan0 ]; then
  if [ -n "$status" ]; then
    status="$status "
  fi
  if [ "$(cat /sys/class/net/wlan0/operstate)" = "up" ]; then
    status="$status󰖩"
    ssid="$(iwgetid | sed 's/wlan0 \+ESSID:"\(.*\)"/\1/')"
    if [ -n "$ssid" ]; then
      status="$status $ssid"
    fi
  else
    status="$status󰖪"
    ex=1
  fi
fi

echo "$status"
exit "$ex"
